import { Roboto } from "next/font/google";
import "./globals.css";

const noto_sans = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Workflow Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>{children}</body>
    </html>
  );
}
